/**
 * Random handle generator — natural-world adjective + noun + 4 digits.
 *
 * **Why:** PRIVACY.md D1/D2 EDITED (2026-05-23) — handle default must NOT
 * derive from the user's email-local-part (would leak real names like
 * `jane.smith` from a `jane.smith@gmail.com` signup). A random natural-world
 * handle is the load-bearing default; users can edit freely but the default
 * never embeds personal data.
 *
 * **Wordlist scope:** ~150 adjectives + ~150 nouns drawn from the natural
 * world — animals, plants, weather, geography. Explicitly avoids:
 *   - Human / identity / cultural terms
 *   - Anything that could read as a slur or in-joke
 *   - Anything that's a common given name
 *
 * Casey to skim before public launch for cultural neutrality (DFS-C1.3).
 *
 * **Format:** `<adjective>-<noun>-<NNNN>` (e.g. `brave-otter-4729`).
 * Total handle space: ~150 × ~150 × 10000 = ~225M unique handles.
 * Collision rate at 10k users ≈ 0.02%; the UNIQUE constraint on
 * public.users.handle handles the rest by failing the INSERT and prompting
 * a re-roll.
 */

export const ADJECTIVES = [
  'brave',
  'calm',
  'swift',
  'silent',
  'quiet',
  'wild',
  'gentle',
  'kind',
  'steady',
  'bold',
  'bright',
  'clear',
  'soft',
  'warm',
  'cool',
  'fresh',
  'ancient',
  'deep',
  'high',
  'low',
  'amber',
  'copper',
  'silver',
  'golden',
  'jade',
  'indigo',
  'crimson',
  'ivory',
  'rust',
  'misty',
  'foggy',
  'sunny',
  'rainy',
  'stormy',
  'snowy',
  'dewy',
  'dusty',
  'frosty',
  'moonlit',
  'distant',
  'hidden',
  'open',
  'wandering',
  'roaming',
  'soaring',
  'flowing',
  'drifting',
  'patient',
  'curious',
  'watchful',
  'alert',
  'hopeful',
  'peaceful',
  'dreaming',
  'woven',
  'vast',
  'tiny',
  'mighty',
  'humble',
  'sturdy',
  'slender',
  'broad',
  'narrow',
  'smooth',
  'rough',
  'lucky',
  'charming',
  'dancing',
  'singing',
  'laughing',
  'smiling',
  'glowing',
  'shining',
  'careful',
  'thoughtful',
  'mindful',
  'ready',
  'willing',
  'eager',
  'glad',
  'proud',
  'true',
  'twilight',
  'dusk',
  'midnight',
  'morning',
  'evening',
  'autumn',
  'winter',
  'spring',
  'tidal',
  'lunar',
  'solar',
  'cosmic',
  'polar',
  'alpine',
  'prairie',
  'coastal',
  'arctic',
  'tropic',
  'temperate',
  'riverside',
  'lakeside',
  'hillside',
  'woodland',
  'rolling',
  'winding',
  'sweeping',
  'climbing',
  'leaping',
  'gliding',
  'hovering',
  'resting',
  'cedar',
  'mossy',
  'fern',
  'pine',
  'oak',
  'birch',
  'maple',
  'willow',
  'aspen',
  'elm',
  'verdant',
  'lush',
  'sparse',
  'rocky',
  'sandy',
  'flinty',
  'pebbled',
  'starlit',
  'cloudy',
  'breezy',
  'gusty',
  'cool',
  'crisp',
  'still',
  'gentle',
  'curious',
  'caring',
  'fair',
  'wise',
  'bright',
  'sincere',
  'earnest',
  'thrifty',
  'frugal',
  'plain',
  'simple',
  'humble',
  'free',
  'mellow',
  'sturdy',
  'lively',
  'spry',
  'nimble',
  'agile',
  'quick',
  'patient',
] as const;

export const NOUNS = [
  'otter',
  'fox',
  'deer',
  'owl',
  'hawk',
  'eagle',
  'heron',
  'crane',
  'raven',
  'wolf',
  'lynx',
  'hare',
  'beaver',
  'badger',
  'mole',
  'vole',
  'weasel',
  'marten',
  'seal',
  'salmon',
  'trout',
  'perch',
  'pike',
  'koi',
  'moth',
  'bee',
  'firefly',
  'dragonfly',
  'mantis',
  'beetle',
  'cricket',
  'finch',
  'robin',
  'wren',
  'swift',
  'swallow',
  'lark',
  'thrush',
  'kingfisher',
  'woodpecker',
  'magpie',
  'cedar',
  'pine',
  'oak',
  'birch',
  'maple',
  'willow',
  'aspen',
  'elm',
  'alder',
  'hemlock',
  'sage',
  'fern',
  'moss',
  'ivy',
  'clover',
  'thistle',
  'heather',
  'juniper',
  'lavender',
  'river',
  'brook',
  'stream',
  'lake',
  'pond',
  'marsh',
  'fjord',
  'bay',
  'creek',
  'harbor',
  'mountain',
  'hill',
  'ridge',
  'peak',
  'valley',
  'meadow',
  'plain',
  'dune',
  'glade',
  'grove',
  'stone',
  'rock',
  'pebble',
  'boulder',
  'cliff',
  'cave',
  'summit',
  'slope',
  'trail',
  'path',
  'cloud',
  'mist',
  'fog',
  'rain',
  'snow',
  'dew',
  'frost',
  'breeze',
  'gust',
  'gale',
  'star',
  'moon',
  'comet',
  'eclipse',
  'aurora',
  'dawn',
  'dusk',
  'twilight',
  'sunrise',
  'island',
  'isle',
  'cove',
  'atoll',
  'peninsula',
  'cape',
  'shore',
  'beach',
  'reef',
  'lagoon',
  'opal',
  'agate',
  'quartz',
  'slate',
  'obsidian',
  'granite',
  'marble',
  'flint',
  'lantern',
  'compass',
  'kettle',
  'basket',
  'satchel',
  'thimble',
  'feather',
  'acorn',
  'pinecone',
  'shell',
  'seedling',
  'sapling',
  'thicket',
  'orchard',
  'pasture',
  'vineyard',
  'mushroom',
  'leaf',
  'petal',
  'bloom',
  'sprout',
  'tendril',
  'root',
  'branch',
] as const;

/** Crypto-safe-ish 4-digit suffix. Math.random is fine here — we're not
 *  generating secrets, just collision-mitigators. The UNIQUE constraint
 *  on public.users.handle is the actual integrity gate. */
function randomFourDigits(): string {
  const n = Math.floor(Math.random() * 10000);
  return n.toString().padStart(4, '0');
}

function pick<T>(arr: readonly T[]): T {
  const i = Math.floor(Math.random() * arr.length);
  // Non-empty arrays — TS strict + noUncheckedIndexedAccess wants a guard.
  const v = arr[i];
  if (v === undefined) throw new Error('Empty wordlist');
  return v;
}

/**
 * Generate a random handle. Pure function (modulo Math.random).
 *
 * Format: `<adjective>-<noun>-<NNNN>` — all lowercase, hyphen-separated,
 * 4-digit zero-padded suffix.
 */
export function generateRandomHandle(): string {
  return `${pick(ADJECTIVES)}-${pick(NOUNS)}-${randomFourDigits()}`;
}

/**
 * Generate N candidate handles. Used by the signup UI to offer the user
 * a few suggestions to pick from.
 */
export function generateHandleSuggestions(count = 3): string[] {
  const seen = new Set<string>();
  while (seen.size < count) {
    seen.add(generateRandomHandle());
  }
  return Array.from(seen);
}
